services:
  - type: web
    name: pixelgrapher
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
