import { execSync, spawn } from 'child_process';
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';

// Helper functions for calendar calculations
function getCalendarRange(year: number) {
  const jan1 = new Date(Date.UTC(year, 0, 1));
  const dec31 = new Date(Date.UTC(year, 11, 31));
  const startOfWeek = new Date(jan1);
  startOfWeek.setUTCDate(jan1.getUTCDate() - jan1.getUTCDay());
  const endOfWeek = new Date(dec31);
  endOfWeek.setUTCDate(dec31.getUTCDate() + (6 - dec31.getUTCDay()));
  const weeksCount = Math.ceil((endOfWeek.getTime() - startOfWeek.getTime()) / (7 * 24 * 60 * 60 * 1000));
  return { startDate: startOfWeek, endDate: endOfWeek, weeksCount };
}

function dateForCell(day: number, week: number, range: any): Date {
  const date = new Date(range.startDate);
  date.setUTCDate(date.getUTCDate() + (week * 7) + day);
  return date;
}

interface CommitConfig {
  date: string;
  count: number;
}

interface GitRepoConfig {
  repoName: string;
  username: string;
  email: string;
  remoteUrl?: string;
}

export class GitOperations {
  private repoPath: string;
  private config: GitRepoConfig;

  constructor(config: GitRepoConfig) {
    this.config = config;
    // Create a temporary directory for the repo
    const tempBase = join(tmpdir(), 'pixelgrapher-repos');
    if (!existsSync(tempBase)) {
      mkdirSync(tempBase, { recursive: true });
    }
    this.repoPath = join(tempBase, `${config.username}-${config.repoName}-${Date.now()}`);
  }

  /**
   * Initialize a new Git repository
   */
  async initRepo(): Promise<void> {
    try {
      // Create directory
      if (!existsSync(this.repoPath)) {
        mkdirSync(this.repoPath, { recursive: true });
      }

      // Initialize git repo
      this.execGitCommand('git init');

      // Configure user
      this.execGitCommand(`git config user.name "${this.config.username}"`);
      this.execGitCommand(`git config user.email "${this.config.email}"`);

      // Create .pixelgrapher directory
      const pixelDir = join(this.repoPath, '.pixelgrapher');
      mkdirSync(pixelDir, { recursive: true });

      // Create initial README
      const readmePath = join(this.repoPath, 'README.md');
      writeFileSync(
        readmePath,
        `# ${this.config.repoName}\n\n🎨 Generated by [PixelGrapher](https://github.com/yourusername/PixelGrapher)\n\nThis repository contains GitHub Contribution Graph art created with PixelGrapher.\nAll commit data is stored in the \`.pixelgrapher/\` directory.\n`
      );

      // Create .gitignore to keep .pixelgrapher visible
      const gitignorePath = join(this.repoPath, '.gitignore');
      writeFileSync(
        gitignorePath,
        `# Keep PixelGrapher commits visible\n!.pixelgrapher/\n`
      );

      // Initial commit
      this.execGitCommand('git add README.md .gitignore');
      this.execGitCommand('git commit -m "Initial commit"');

    } catch (error: any) {
      throw new Error(`Failed to initialize repository: ${error.message}`);
    }
  }

  /**
   * Create a commit with a specific date
   */
  async createCommit(date: string, index: number): Promise<void> {
    try {
      // Create .pixelgrapher directory if it doesn't exist
      const pixelDir = join(this.repoPath, '.pixelgrapher');
      if (!existsSync(pixelDir)) {
        mkdirSync(pixelDir, { recursive: true });
      }

      // Create a unique file inside .pixelgrapher folder
      const fileName = `commit-${date}-${index}.txt`;
      const filePath = join(pixelDir, fileName);
      
      // Write content to file
      const timestamp = new Date().toISOString();
      writeFileSync(
        filePath,
        `PixelGrapher Commit\nDate: ${date}\nIndex: ${index}\nGenerated: ${timestamp}\n`
      );

      // Add file (use relative path from repo root)
      this.execGitCommand(`git add ".pixelgrapher/${fileName}"`);

      // Create commit with backdated timestamp in UTC noon to match GitHub's calendar
      // GitHub contribution graph uses UTC dates, so we use noon UTC to avoid timezone edge cases
      const commitDate = `${date}T12:00:00Z`;
      const commitMessage = `PixelGrapher art (${date})`;

      this.execGitCommand(
        `git commit -m "${commitMessage}"`,
        {
          GIT_AUTHOR_DATE: commitDate,
          GIT_COMMITTER_DATE: commitDate,
        }
      );

    } catch (error: any) {
      throw new Error(`Failed to create commit for ${date}: ${error.message}`);
    }
  }

  /**
   * Add remote repository
   */
  async addRemote(remoteUrl: string): Promise<void> {
    try {
      this.execGitCommand(`git remote add origin "${remoteUrl}"`);
    } catch (error: any) {
      // Remote might already exist
      if (error.message.includes('already exists')) {
        this.execGitCommand(`git remote set-url origin "${remoteUrl}"`);
      } else {
        throw new Error(`Failed to add remote: ${error.message}`);
      }
    }
  }

  /**
   * Push commits to remote repository
   */
  async push(branch: string = 'main'): Promise<void> {
    try {
      // Try to set default branch to main
      this.execGitCommand(`git branch -M ${branch}`);
      
      // Push with force to ensure all commits are uploaded
      this.execGitCommand(`git push -u origin ${branch} --force`);
    } catch (error: any) {
      throw new Error(`Failed to push commits: ${error.message}`);
    }
  }

  /**
   * Execute a git command in the repository directory
   */
  private execGitCommand(command: string, envVars?: Record<string, string>): string {
    try {
      const result = execSync(command, {
        cwd: this.repoPath,
        encoding: 'utf-8',
        env: {
          ...process.env,
          ...envVars,
        },
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      return result.trim();
    } catch (error: any) {
      throw new Error(`Git command failed: ${command}\n${error.message}`);
    }
  }

  /**
   * Clean up the temporary repository
   */
  cleanup(): void {
    try {
      if (existsSync(this.repoPath)) {
        rmSync(this.repoPath, { recursive: true, force: true });
      }
    } catch (error) {
      console.error('Failed to cleanup repository:', error);
    }
  }

  /**
   * Get the repository path
   */
  getRepoPath(): string {
    return this.repoPath;
  }
}

/**
 * Generate commit plan from grid data
 */
export function generateCommitPlan(
  grid: number[][],
  year: number,
  baseIntensity: number
): CommitConfig[] {
  const commitPlan: CommitConfig[] = [];
  const range = getCalendarRange(year);

  const weeks = grid[0]?.length ?? range.weeksCount;
  const days = Math.min(7, grid.length);

  for (let week = 0; week < weeks; week++) {
    for (let day = 0; day < days; day++) {
      const intensity = grid[day][week] ?? 0;
      if (intensity <= 0) continue;

      const date = dateForCell(day, week, range);
      if (date.getUTCFullYear() !== year) continue;

      const commitCount = intensity * baseIntensity;
      commitPlan.push({
        date: date.toISOString().split('T')[0],
        count: commitCount,
      });
    }
  }

  return commitPlan;
}

/**
 * Sleep utility for delays
 */
export function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
