import * as git from 'isomorphic-git';
import http from 'isomorphic-git/http/node';
import { Volume } from 'memfs';

// Helper functions for calendar calculations
function getCalendarRange(year: number) {
  const jan1 = new Date(Date.UTC(year, 0, 1));
  const dec31 = new Date(Date.UTC(year, 11, 31));
  const startOfWeek = new Date(jan1);
  startOfWeek.setUTCDate(jan1.getUTCDate() - jan1.getUTCDay());
  const endOfWeek = new Date(dec31);
  endOfWeek.setUTCDate(dec31.getUTCDate() + (6 - dec31.getUTCDay()));
  const weeksCount = Math.ceil((endOfWeek.getTime() - startOfWeek.getTime()) / (7 * 24 * 60 * 60 * 1000));
  return { startDate: startOfWeek, endDate: endOfWeek, weeksCount };
}

function dateForCell(day: number, week: number, range: any): Date {
  const date = new Date(range.startDate);
  date.setUTCDate(date.getUTCDate() + (week * 7) + day);
  return date;
}

interface CommitConfig {
  date: string;
  count: number;
}

interface GitRepoConfig {
  repoName: string;
  username: string;
  email: string;
  remoteUrl?: string;
}

export class GitOperations {
  private repoDir: string;
  private config: GitRepoConfig;
  private fs: any;

  constructor(config: GitRepoConfig) {
    this.config = config;
    // Create an isolated in-memory file system for this repository
    this.fs = Volume.fromJSON({});
    this.repoDir = '/repo';
  }

  /**
   * Initialize a new Git repository
   */
  async initRepo(): Promise<void> {
    try {
      this.fs.mkdirSync(this.repoDir, { recursive: true });

      // Initialize git repo
      await git.init({ fs: this.fs, dir: this.repoDir, defaultBranch: 'main' });

      // Create .pixelgrapher directory
      const pixelDir = `${this.repoDir}/.pixelgrapher`;
      this.fs.mkdirSync(pixelDir, { recursive: true });

      // Create initial README
      const readmePath = `${this.repoDir}/README.md`;
      this.fs.writeFileSync(
        readmePath,
        `# ${this.config.repoName}\n\n🎨 Generated by [PixelGrapher](https://github.com/WulfaW/PixelGrapher)\n\nThis repository contains GitHub Contribution Graph art created with PixelGrapher.\nAll commit data is stored in the \`.pixelgrapher/\` directory.\n`
      );

      // Create .gitignore to keep .pixelgrapher visible
      const gitignorePath = `${this.repoDir}/.gitignore`;
      this.fs.writeFileSync(
        gitignorePath,
        `# Keep PixelGrapher commits visible\n!.pixelgrapher/\n`
      );

      // Initial commit
      await git.add({ fs: this.fs, dir: this.repoDir, filepath: 'README.md' });
      await git.add({ fs: this.fs, dir: this.repoDir, filepath: '.gitignore' });

      await git.commit({
        fs: this.fs,
        dir: this.repoDir,
        author: {
          name: this.config.username,
          email: this.config.email,
        },
        message: 'Initial commit'
      });

    } catch (error: any) {
      throw new Error(`Failed to initialize repository: ${error.message}`);
    }
  }

  /**
   * Create a commit with a specific date
   */
  async createCommit(date: string, index: number): Promise<void> {
    try {
      const pixelDir = `${this.repoDir}/.pixelgrapher`;
      if (!this.fs.existsSync(pixelDir)) {
        this.fs.mkdirSync(pixelDir, { recursive: true });
      }

      const fileName = `commit-${date}-${index}.txt`;
      const filePath = `${pixelDir}/${fileName}`;

      const timestamp = new Date().toISOString();
      this.fs.writeFileSync(
        filePath,
        `PixelGrapher Commit\nDate: ${date}\nIndex: ${index}\nGenerated: ${timestamp}\n`
      );

      await git.add({ fs: this.fs, dir: this.repoDir, filepath: `.pixelgrapher/${fileName}` });

      // GitHub calendar requires UTC dates. Let's use noon UTC.
      const commitDate = new Date(`${date}T12:00:00Z`);
      const timestampSeconds = Math.floor(commitDate.getTime() / 1000);

      await git.commit({
        fs: this.fs,
        dir: this.repoDir,
        author: {
          name: this.config.username,
          email: this.config.email,
          timestamp: timestampSeconds,
          timezoneOffset: 0
        },
        committer: {
          name: this.config.username,
          email: this.config.email,
          timestamp: timestampSeconds,
          timezoneOffset: 0
        },
        message: `PixelGrapher art (${date})`
      });

    } catch (error: any) {
      throw new Error(`Failed to create commit for ${date}: ${error.message}`);
    }
  }

  /**
   * Add remote repository
   */
  async addRemote(remoteUrl: string): Promise<void> {
    try {
      await git.addRemote({
        fs: this.fs,
        dir: this.repoDir,
        remote: 'origin',
        url: remoteUrl
      });
    } catch (error: any) {
      throw new Error(`Failed to add remote: ${error.message}`);
    }
  }

  /**
   * Push commits to remote repository
   */
  async push(branch: string = 'main', token?: string): Promise<void> {
    try {
      const pushConfig: any = {
        fs: this.fs,
        http,
        dir: this.repoDir,
        remote: 'origin',
        ref: branch,
        force: true
      };

      if (token) {
        pushConfig.onAuth = () => ({ username: token });
      }

      await git.push(pushConfig);
    } catch (error: any) {
      throw new Error(`Failed to push commits: ${error.message}`);
    }
  }

  /**
   * Clean up the temporary repository (for memfs this just resets it)
   */
  cleanup(): void {
    try {
      this.fs.reset();
    } catch (error) {
      console.error('Failed to cleanup memory repository:', error);
    }
  }

  /**
   * Get the repository path
   */
  getRepoPath(): string {
    return this.repoDir;
  }

  /**
   * Reset the repository to a clean state
   */
  async resetRepo(remoteUrl: string, branch: string = 'main', token?: string): Promise<void> {
    try {
      this.fs.reset();
      await this.initRepo();
      await this.addRemote(remoteUrl);
      await this.push(branch, token);
    } catch (error: any) {
      throw new Error(`Failed to reset repository: ${error.message}`);
    }
  }
}

/**
 * Generate commit plan from grid data
 */
export function generateCommitPlan(
  grid: number[][],
  year: number,
  baseIntensity: number
): CommitConfig[] {
  const commitPlan: CommitConfig[] = [];
  const range = getCalendarRange(year);

  const weeks = grid[0]?.length ?? range.weeksCount;
  const days = Math.min(7, grid.length);

  for (let week = 0; week < weeks; week++) {
    for (let day = 0; day < days; day++) {
      const intensity = grid[day][week] ?? 0;
      if (intensity <= 0) continue;

      const date = dateForCell(day, week, range);
      if (date.getUTCFullYear() !== year) continue;

      const commitCount = intensity * baseIntensity;
      commitPlan.push({
        date: date.toISOString().split('T')[0],
        count: commitCount,
      });
    }
  }

  return commitPlan;
}

/**
 * Sleep utility for delays
 */
export function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
